### ISSUE TITLE
Inform users explicit about the required shift for pause

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#63]
Pulled #56 to here (a part of it)

**Comment by nonnymoose** [comment]
@lezsakdomi Can I see the output of your `xmodmap -pke`?

**Comment by lezsakdomi** [comment]
@nonnymoose Yes, of course. http://termbin.com/gfhs

`xinput --test-xi2` says (filtered):
```
EVENT type 13 (RawKeyPress)
    device: 3 (8)
    detail: 127
    valuators:

EVENT type 2 (KeyPress)
    device: 8 (8)
    detail: 127
    flags: 
    root: 166.00/879.00
    event: 166.00/879.00
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x4a3 event 0x4a3 child 0x2156a1e
EVENT type 14 (RawKeyRelease)
    device: 3 (8)
    detail: 127
    valuators:

EVENT type 3 (KeyRelease)
    device: 8 (8)
    detail: 127
    flags: 
    buttons:
    modifiers: locked 0x10 latched 0 base 0 effective: 0x10
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
```
